### ISSUE TITLE
add mappings to OMIM phenotypic series

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/human-disease-ontology#1]
we can use the phenotypic series from OMIM as some grouping classes.  The phenoseries ids are part of the omim file, here:
http://nif-crawler.neuinfo.org/monarch/ttl/omim.ttl

see ticket here:
https://github.com/obophenotype/human-disease-ontology/issues/25

**Comment by cmungall** [comment]
This issue was moved to monarch-initiative/monarch-disease-ontology#5
