### ISSUE TITLE
Bin all OMIM IDs under 'genetic disease'

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/human-disease-ontology#10]
All OMIMs are genetic. We should ensure each one is classified here, directly or indirectly. Note that it's not clear which orphanets belong under here.

In future we may want to try representing this in a way that doesn't overload isa - e.g. with an etiology field

**Comment by nicolevasilevsky** [comment]
This issue was moved to monarch-initiative/monarch-disease-ontology#18
