### ISSUE TITLE
Grouping classes for DCs

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/human-disease-ontology#11]
We should manually curate groupings at the level above DC

See for example, subtypes of epilepsy, that should be under DOID:1826 ! epilepsy syndrome

![screen shot 2015-03-12 at 9 49 47 pm](https://cloud.githubusercontent.com/assets/50745/6633971/659e792e-c90e-11e4-8109-897b1875bd0c.png)

**Comment by cmungall** [comment]
@sbello is it OK to add xrefs and/or synonyms to DCs in the main omimclusters.obo file?

For example, currently text matching with DO is failing on this case. My lexical reordering doesnt work with compound words. If we add a synonym (or direct xref) this will help:

![screen shot 2015-03-17 at 2 39 33 pm](https://cloud.githubusercontent.com/assets/50745/6698150/74541fd4-ccb3-11e4-88c7-3d81bca1e5bf.png)

**Comment by sbello** [comment]
Yes, xrefs and synonyms are fine.

**Comment by nicolevasilevsky** [comment]
This issue was moved to monarch-initiative/monarch-disease-ontology#19
