### ISSUE TITLE
SHOUTY ALL CAPS sneaking back in

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/human-disease-ontology#18]
probably coming from omimclusters, which has its own pipeline for pulling in omim. We should swap in our version

**Comment by mellybelly** [comment]
would also be great to have better descriptions that @nlwashington created. @sbello check impact on MGI

**Comment by sbello** [comment]
MGI has a separate translation process that occurs during the OMIM load. Changing names of OMIM terms in the omimclusters file would have no impact on MGI.

**Comment by nlwashington** [comment]
you can see the label scrubbing i do in dipper for OMIM here:
https://github.com/monarch-initiative/dipper/blob/master/dipper/sources/OMIM.py

in the function _cleanup_label it involves:
1. remove the abbreviation suffixes
2. convert the roman numerals to integer numbers
3. make the text title case, except for conjunctions/prepositions/articles

**Comment by nicolevasilevsky** [comment]
This issue was moved to monarch-initiative/monarch-disease-ontology#26
