### ISSUE TITLE
Adding groupings for DECIPHER

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/human-disease-ontology#19]
How is this coming along?

**Comment by nicolevasilevsky** [comment]
I haven't worked on this yet, I am working on mappingDC_Orphanet_DO.xlsx file right now with Sue. Is the groupings for DECIPHER higher priority?

**Comment by mellybelly** [comment]
What should we do with ones that really can't be classified?

**Comment by cmungall** [comment]
I think this is going to be easiest to do by hand editing the obo file

**Comment by cmungall** [comment]
Can you spot check the commits I made?

https://github.com/monarch-initiative/human-disease-ontology/commit/9ef0ea01a7d3c18e24ed326bcf1c5ccfd9f104c1

**Comment by cmungall** [comment]
@mellybelly I just put these under 'syndrome' for now

**Comment by nicolevasilevsky** [comment]
Not sure if you are asking @mellybelly or me to spot check your commits, but I am having trouble opening the file. The file is: decipherclusters.obo, right?

![image](https://cloud.githubusercontent.com/assets/6722114/6695939/78f1ae96-cca2-11e4-8ced-4edd64beb3d4.png)

**Comment by cmungall** [comment]
Just click on this to see the commits: 
https://github.com/monarch-initiative/human-disease-ontology/commit/9ef0ea01a7d3c18e24ed326bcf1c5ccfd9f104c1

**Comment by nicolevasilevsky** [comment]
I see. I think it looks good. (However, I am unfamiliar with the children of leukodystrophy, so I cannot comment if those are correctly classified.)

**Comment by nicolevasilevsky** [comment]
is there still something that needs to be done or can we close this ticket?

**Comment by nicolevasilevsky** [comment]
This issue was moved to monarch-initiative/monarch-disease-ontology#28
