### ISSUE TITLE
dysequillibrium syndrome

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/human-disease-ontology#20]
- DC is probably the same as the ORDO here
- the ORDO hierarchy doesn't join up as well as it should here. Not much we can do about this.

![screen shot 2015-03-17 at 2 45 04 pm](https://cloud.githubusercontent.com/assets/50745/6698260/8062211c-ccb4-11e4-98c8-c152aaa6d921.png)

**Comment by nicolevasilevsky** [comment]
This issue was moved to monarch-initiative/monarch-disease-ontology#29
