### ISSUE TITLE
Get definitions

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/human-disease-ontology#25]
As part of of the build we need to pull the definitions from DO, OMIM, and orphanet, with some order of priority. @nlwashington has built the OMIM and GeneReview text descriptions, these should be relatively easy to pull together with DO terms? then we could potentially identify terms with no definitions (eg. DC terms).

**Comment by cmungall** [comment]
http://nif-crawler.neuinfo.org/monarch/ttl/ 
genereviews.ttl has labels syns but not defs

**Comment by mellybelly** [comment]
I believe @nlwashington is working on licensing issues but hopefully soon defs too.

**Comment by nlwashington** [comment]
awaiting licensing from GR/UW Tech Transfer office.  hoping to have another call with them next week.

**Comment by nlwashington** [comment]
do you think we should try to get some kind of licensing for http://www.merckmanuals.com/#three ?

**Comment by nicolevasilevsky** [comment]
This issue was moved to monarch-initiative/monarch-disease-ontology#34
