### ISSUE TITLE
Evaluate disease to phenotype seeming equivalents

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/human-disease-ontology#29]
There are many HP and DOIDs with the same label (thankfully HP uses a leading upper case, usually annoying, but this saves us in Protege, where the same label causes massive issues).

I would rather see explicit different labels otherwise this will cause massive confusion.

Also these equivalent labels could be used to generate axioms - not equivalent classes, but something like 'has hallmark phenotype'?

**Comment by nlwashington** [comment]
+1

**Comment by nicolevasilevsky** [comment]
This issue was moved to monarch-initiative/monarch-disease-ontology#38
