### ISSUE TITLE
add KEGG disease ids

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/human-disease-ontology#3]
Here's the KEGG disease id to OMIM disease id map:
http://rest.genome.jp/link/disease/omim

note that is is a 1:many relationship (so they are often grouping classes).

there are some distinct disease-gene associations in kegg, so having their disease ids would be really helpful.

**Comment by nlwashington** [comment]
note that these are different than the "disease pathways".

**Comment by nlwashington** [comment]
there's definitely some oddities.  for example:
http://www.kegg.jp/dbget-bin/www_bget?ds:H00493

this is clearly a grouping class, as it is named:
Heparan sulfate proteoglycan gene defects, including:
Dyssegmental dysplasia, Silverman-Handmaker type;
Schwartz-Jampel syndrome;
Simpson-Golabi-Behmel syndrome, type 1;
Omodysplasia 1;
Multiple exostoses

which includes 5 diseases, that aren't themselves identified with kegg ids.  the genes for the specific sub-types are mapped to the grouping class rather than the specific disease, which is really unfortunate.

**Comment by cmungall** [comment]
Just FYI the LCS of those 6 OMIMs in 'bone disease'

![kegg](https://cloud.githubusercontent.com/assets/50745/7264536/4d717d7c-e841-11e4-9e63-d913739ab73b.png)

**Comment by nlwashington** [comment]
i notice only a couple of the diseases are linked to something with "perlecan" in it.  I didn't know what that was, so i looked:
Perlecan (PLC) also known as basement membrane-specific heparan sulfate proteoglycan core protein (HSPG) or heparan sulfate proteoglycan 2 (HSPG2), is a protein that in humans is encoded by the HSPG2 gene.

I wonder if there are missing links?

but it looks like the LCS is actually just "disease", though most are LCS with "bone disease".  Simpson-Golabl-Behmel is missing out ?

**Comment by cmungall** [comment]
Ah yes you're right, Simpson-Golabl-Behmel is effectively unclassified

**Comment by nlwashington** [comment]
what is the URI for kegg disease identifiers?  for example:
http://www.kegg.jp/dbget-bin/www_bget?ds:H00060

in dipper, i could add equivalence axioms between kegg disease ids and omim disease ids if they are 1:1.  this is a very conservative estimate.  would you like that?

**Comment by nlwashington** [comment]
there are also ~73 KEGG diseases that have no omim mappings, but do have disease-gene associations.  for example:
http://www.kegg.jp/dbget-bin/www_bget?ds:H00014

be sure you get these into mondo!

**Comment by cmungall** [comment]
This issue was moved to monarch-initiative/monarch-disease-ontology#7
