### ISSUE TITLE
Additional diseases in NDFRT drug files

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/human-disease-ontology#31]
These are likely in the UMLS but we'll want them so as to associate drug-disease relationships. 
@ShahimEssaid working on NDFRT but maybe can grab the disease graph and ensure we have those classes/xrefs in MonDO

http://evs.nci.nih.gov/ftp1/NDF-RT/

**Comment by mellybelly** [comment]
see also http://rxnav.nlm.nih.gov/RxNavDoc.html to view the whole content.

**Comment by nicolevasilevsky** [comment]
This issue was moved to monarch-initiative/monarch-disease-ontology#40
