### ISSUE TITLE
Verify: Pemphigus

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/human-disease-ontology#34]
We are missing some links here; 

![pemphigus](https://cloud.githubusercontent.com/assets/50745/7663992/9b068252-fb2a-11e4-9dd8-752c60c88af0.png)
- blue = DO
- yellow = ORDO
- brown = OMIM
- grey = MESH

Should DOID:9182 ! pemphigus be merged into Orphanet:79669 ! Autoimmune bullous skin disease?

**Comment by nicolevasilevsky** [comment]
This issue was moved to monarch-initiative/monarch-disease-ontology#42
