### ISSUE TITLE
add medgen disease id mappings

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/human-disease-ontology#4]
please add medgen ids to the uberdisease ontology for xrefs.  these will be useful for linking with clinvar data.
http://www.ncbi.nlm.nih.gov/medgen/docs/faq/#rel

also found this possibly relevant:
ftp://ftp.ncbi.nih.gov/pub/medgen/MedGen_HPO_OMIM_Mapping.txt.gz

ftp://ftp.ncbi.nih.gov/gene/DATA/mim2gene_medgen

also see related https://github.com/monarch-initiative/disease-miner/issues/5
and https://support.crbs.ucsd.edu/browse/NIF-11766

**Comment by nlwashington** [comment]
Also note that the medgen-to-omim (and other vocab) mappings here can't be trusted as equivalence classes. For example, for Hermasky-Pudluck syndrome,
http://beta.neuinfo.org/mynif/search.php?q=DOID_3753&dis=Hermansky-Pudlak%20syndrome&t=indexable&nif=nlx_151671-4&b=0&r=20
it has several subtypes; each one maps to GeneReviews:NBK1287, which is for a general type of Hermansky-Pudlak.

**Comment by mellybelly** [comment]
yeah i think i would want to manually review all medgen xrefs...

**Comment by cmungall** [comment]
This issue was moved to monarch-initiative/monarch-disease-ontology#8
