### ISSUE TITLE
Decouple this repo from fork

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/human-disease-ontology#40]
It probably makes sense to make this repo standalone rather than a fork, as it currently is

can be done this way
https://help.github.com/articles/duplicating-a-repository/

But ideally we would preserve tickets too

See hints here:
https://github.com/holman/ama/issues/413

**Comment by cmungall** [comment]
See the README.md: https://github.com/monarch-initiative/monarch-disease-ontology

**Comment by cmungall** [comment]
Need to move issues

This does it 1 at a time
https://github-issue-mover.appspot.com/
A bit tedious... not sure if there is a faster way

**Comment by mellybelly** [comment]
@cmungall if you show @nicolevasilevsky how to do it I am sure she would be willing to help

**Comment by cmungall** [comment]
Instructions:
1. go to https://github-issue-mover.appspot.com/
2. Authorize
3. In "Issue to move field" field enter `monarch-initiative/human-disease-ontology#1`
4. In "Destination" field enter `monarch-initiative/monarch-disease-ontology`  (note: no number)
5. Click "Move issue"
6. Go back to step 3, and replace "1" with "2" and so on, until all done

**Comment by cmungall** [comment]
I did 1-9, so start at `#10`. It will map to 15 in the new. Don't worry

**Comment by nicolevasilevsky** [comment]
working on this now

**Comment by nicolevasilevsky** [comment]
This issue was moved to monarch-initiative/monarch-disease-ontology#48
