### ISSUE TITLE
fix SNOMED prefixes

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/human-disease-ontology#5]
currently, ids for SNOMED are formed like:

SNOMEDCT_2010_1_31:154999006

is it necessary to code the date/version information into the prefix? shouldn't this just be SNOMEDCT?

also in ticket: https://support.crbs.ucsd.edu/browse/NIF-11604

**Comment by mellybelly** [comment]
It should just be SNOMEDCT, we should be able to include the version used in the file header

**Comment by cmungall** [comment]
This issue was moved to monarch-initiative/monarch-disease-ontology#9
